apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-api-pedido
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-api-pedido
  template:
    metadata:
      labels:
        app: techlanches-api-pedido
    spec:
      containers:
        - name: techlanches-api-pedido
          image: g124soat/techlanches-pedido:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: techlanches-api-pedido-service
  namespace: techlanches
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: techlanches-api-pedido
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
  type: LoadBalancer
