apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-worker-producao
  namespace: techlanches
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techlanches-worker-producao
  template:
    metadata:
      labels:
        app: techlanches-worker-producao
    spec:
      containers:
        - name: techlanches-worker-producao
          image: g124soat/techlanches-worker:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 20
