apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-api-pedido
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-api-pedido
  template:
    metadata:
      labels:
        app: techlanches-api-pedido
    spec:
      containers:
        - name: techlanches-api-pedido
          image: g124soat/techlanches-pedido:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: DOTNET_ENVIRONMENT
              valueFrom: 
                configMapKeyRef:
                  name: api-pedido-configmap
                  key: DotnetEnviroment
            - name: PAGAMENTO_SERVICE
              valueFrom: 
                configMapKeyRef:
                  name: api-pagamento-configmap
                  key: ServiceName
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: api-pedido-service
  namespace: techlanches
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: techlanches-api-pedido
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 8080
  type: LoadBalancer
